import type { Job } from "@/types/job";

export const MOCK_JOBS: Job[] = [
  {
    id: "senior-frontend-engineer",
    title: "Senior Frontend Engineer",
    department: "Engineering",
    location: "San Francisco, CA",
    locationType: "Hybrid",
    employmentType: "Full-time",
    experienceLevel: "Senior",
    description: "We're looking for a Senior Frontend Engineer to join our growing team and help build the next generation of our product. You'll work closely with designers and backend engineers to create exceptional user experiences.",
    responsibilities: [
      "Design and implement responsive, performant user interfaces using React and TypeScript",
      "Collaborate with designers to translate designs into high-quality code",
      "Optimize application performance and ensure cross-browser compatibility",
      "Mentor junior engineers and contribute to engineering best practices",
      "Participate in code reviews and architectural decisions",
    ],
    requirements: [
      "5+ years of experience in frontend development",
      "Expert knowledge of React, TypeScript, and modern CSS",
      "Strong understanding of web performance optimization",
      "Experience with state management libraries (Redux, Zustand, etc.)",
      "Excellent communication and collaboration skills",
    ],
    niceToHave: [
      "Experience with Next.js and server-side rendering",
      "Familiarity with design systems and component libraries",
      "Contributions to open-source projects",
      "Experience with testing frameworks (Jest, Playwright, Cypress)",
    ],
    salaryRange: {
      min: 150000,
      max: 200000,
      currency: "USD",
    },
    postedDate: new Date("2026-01-15"),
    applicationUrl: "/apply/senior-frontend-engineer",
  },
  {
    id: "product-designer",
    title: "Product Designer",
    department: "Design",
    location: "New York, NY",
    locationType: "Hybrid",
    employmentType: "Full-time",
    experienceLevel: "Mid",
    description: "Join our design team to create beautiful, intuitive products that delight our users. You'll own the end-to-end design process from research to final implementation.",
    responsibilities: [
      "Lead design projects from concept to delivery",
      "Create wireframes, prototypes, and high-fidelity designs",
      "Conduct user research and usability testing",
      "Collaborate with engineers to ensure design implementation quality",
      "Maintain and evolve our design system",
    ],
    requirements: [
      "3+ years of product design experience",
      "Strong portfolio demonstrating UX/UI design skills",
      "Proficiency in Figma and other design tools",
      "Experience with user research methodologies",
      "Understanding of front-end development principles",
    ],
    niceToHave: [
      "Experience designing for B2B SaaS products",
      "Motion design and prototyping skills",
      "Familiarity with accessibility standards (WCAG)",
    ],
    salaryRange: {
      min: 110000,
      max: 150000,
      currency: "USD",
    },
    postedDate: new Date("2026-01-20"),
    applicationUrl: "/apply/product-designer",
  },
  {
    id: "backend-engineer",
    title: "Backend Engineer",
    department: "Engineering",
    location: "Remote",
    locationType: "Remote",
    employmentType: "Full-time",
    experienceLevel: "Mid",
    description: "We're seeking a talented Backend Engineer to help us scale our infrastructure and build robust APIs. You'll work on challenging problems involving distributed systems and data processing.",
    responsibilities: [
      "Design and implement scalable backend services and APIs",
      "Write clean, maintainable, and well-tested code",
      "Optimize database queries and improve system performance",
      "Collaborate with frontend engineers on API design",
      "Participate in on-call rotation and incident response",
    ],
    requirements: [
      "3+ years of backend development experience",
      "Strong proficiency in Node.js, Python, or Go",
      "Experience with relational databases (PostgreSQL, MySQL)",
      "Understanding of RESTful API design and GraphQL",
      "Familiarity with cloud platforms (AWS, GCP, or Azure)",
    ],
    niceToHave: [
      "Experience with microservices architecture",
      "Knowledge of containerization (Docker, Kubernetes)",
      "Experience with message queues and event-driven systems",
      "Understanding of DevOps practices and CI/CD",
    ],
    salaryRange: {
      min: 120000,
      max: 160000,
      currency: "USD",
    },
    postedDate: new Date("2026-01-25"),
    applicationUrl: "/apply/backend-engineer",
  },
  {
    id: "marketing-manager",
    title: "Marketing Manager",
    department: "Marketing",
    location: "Austin, TX",
    locationType: "On-site",
    employmentType: "Full-time",
    experienceLevel: "Senior",
    description: "Lead our marketing efforts and drive growth through strategic campaigns and brand initiatives. You'll manage a small team and work cross-functionally to achieve business goals.",
    responsibilities: [
      "Develop and execute comprehensive marketing strategies",
      "Manage marketing budget and ROI tracking",
      "Lead content creation and brand messaging",
      "Analyze campaign performance and optimize based on data",
      "Manage and mentor a team of marketing specialists",
    ],
    requirements: [
      "5+ years of marketing experience, preferably in tech",
      "Proven track record of successful campaign management",
      "Strong analytical skills and data-driven decision making",
      "Experience with marketing automation tools and CRM systems",
      "Excellent written and verbal communication skills",
    ],
    niceToHave: [
      "Experience in B2B SaaS marketing",
      "Knowledge of SEO and content marketing strategies",
      "Familiarity with growth marketing and experimentation",
    ],
    salaryRange: {
      min: 100000,
      max: 140000,
      currency: "USD",
    },
    postedDate: new Date("2026-01-28"),
    applicationUrl: "/apply/marketing-manager",
  },
  {
    id: "data-scientist-intern",
    title: "Data Science Intern",
    department: "Data",
    location: "Remote",
    locationType: "Remote",
    employmentType: "Internship",
    experienceLevel: "Entry",
    description: "Join our data team for a summer internship where you'll work on real projects involving machine learning and data analysis. This is a great opportunity to gain hands-on experience in a fast-paced startup environment.",
    responsibilities: [
      "Assist in building and improving machine learning models",
      "Analyze large datasets to extract actionable insights",
      "Create visualizations and reports for stakeholders",
      "Collaborate with engineers to deploy models to production",
      "Participate in team meetings and learning sessions",
    ],
    requirements: [
      "Currently pursuing a degree in Computer Science, Statistics, or related field",
      "Strong foundation in statistics and machine learning concepts",
      "Proficiency in Python and data analysis libraries (pandas, numpy)",
      "Excellent problem-solving skills",
      "Ability to communicate technical concepts clearly",
    ],
    niceToHave: [
      "Experience with deep learning frameworks (PyTorch, TensorFlow)",
      "Familiarity with SQL and data warehousing",
      "Previous internship or research experience",
    ],
    postedDate: new Date("2026-02-01"),
    applicationUrl: "/apply/data-scientist-intern",
  },
];
